name: Staging

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ assigned, opened, synchronize, reopened ]

jobs:
  staging-build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test full-install
        run: |
          sudo ./full-install.sh

      - name: Create release
        run: |
          cd ..
          sudo tar -czvf light-proxy.tar.gz light-proxy/
      - name: Release latest
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: staged/v0.x
          files: |
            ../light-proxy.tar.gz
